"""
Owner display name to unit hostname.

The single definition used by both the unprivileged pairing portal and the
root commit helper, so the two sides of the privilege boundary cannot disagree
about what a name becomes.

A slug is an RFC 1123 label: lowercase [a-z0-9-], 1-63 characters, no leading
or trailing hyphen. A name is refused when its slug would contain a
hostname-shaped entry of the sanitization banlist, because the hostname is
broadcast over mDNS and written into the rootfs.

Only (length, sha256) pairs ship, in arlowe_hostname_banlist.json, generated by
scripts/sanitize/gen-hostname-banlist.py. The literal banlist must never ship:
check.sh --scan-dir over the assembled rootfs would flag it. Residual risk,
accepted in ADR-0012: the sha256 of a short literal lets someone who already
has a guess confirm it.

stdlib only; runs under the image's system python3.
"""

import hashlib
import json
import os
import re
import unicodedata
from pathlib import Path

MAX_DISPLAY_NAME = 32
MAX_LABEL = 63
DEFAULT_BANLIST = Path(__file__).with_name("arlowe_hostname_banlist.json")
RESERVED = frozenset({"localhost"})

_REASONS = {
    "empty": "Enter a name for this Arlowe.",
    "too_long": f"Use at most {MAX_DISPLAY_NAME} characters.",
    "no_usable_characters": "Use at least one letter or digit (a-z, 0-9).",
    "reserved": "That name is reserved. Choose another.",
    "not_allowed": "That name is not allowed. Choose another.",
}


class HostnameRejected(ValueError):
    """A display name that cannot become a hostname. `reason` is a stable code."""

    def __init__(self, reason):
        self.reason = reason
        super().__init__(_REASONS[reason])


def slugify(name):
    folded = unicodedata.normalize("NFKD", name)
    folded = "".join(c for c in folded if not unicodedata.combining(c)).lower()
    slug = re.sub(r"[^a-z0-9]+", "-", folded).strip("-")
    return slug[:MAX_LABEL].strip("-")


def _load_banlist():
    path = os.environ.get("ARLOWE_HOSTNAME_BANLIST") or DEFAULT_BANLIST
    with open(path, encoding="utf-8") as f:
        return [(int(e["length"]), e["sha256"]) for e in json.load(f)]


def _contains_banned(slug):
    for length, digest in _load_banlist():
        for i in range(len(slug) - length + 1):
            if hashlib.sha256(slug[i : i + length].encode()).hexdigest() == digest:
                return True
    return False


def validate_display_name(name):
    """Return (display_name, slug) or raise HostnameRejected."""
    display = name.strip()
    if not display:
        raise HostnameRejected("empty")
    if len(display) > MAX_DISPLAY_NAME:
        raise HostnameRejected("too_long")
    slug = slugify(display)
    if not slug:
        raise HostnameRejected("no_usable_characters")
    if slug in RESERVED or slug.isdigit():
        raise HostnameRejected("reserved")
    if _contains_banned(slug):
        raise HostnameRejected("not_allowed")
    return display, slug
